"$schema" = "./node_modules/wrangler/config-schema.json"

name = "me-samh-page-worker"
compatibility_date = "2026-02-19"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
workers_dev = false
preview_urls = false

[[routes]]
pattern = "me.samh.page"
custom_domain = true

[assets]
directory = "dist"
not_found_handling = "single-page-application"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = true
